### PR TITLE
feat: support ESLint 8.x

### LINKED ISSUE #68: Support ESLint 8
ESLint v8 has released.

### PR DESCRIPTION
**Pull request by KKoukiou**
Fixes #68

**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[X] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Update needed dependencies and tests

**Which issue (if any) does this pull request address?**
Support ESlint 8.x

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Review by theoludwig — APPROVED** [review]
Thanks for your contribution. :smile:
LGTM! :+1:

**Review by LinusU — APPROVED** [review]
Nice! 🚀

**Comment by 52541** [comment]
What can I do to help? I will try.

**Comment by KKoukiou** [comment]
Hi :) can i help to get this unblocked? It's prohibiting consumer projects to start using ESLint 8.x.

**Comment by theoludwig** [comment]
> Hi :) can i help to get this unblocked? It's prohibiting consumer projects to start using ESLint 8.x.

Merged, thanks again for your contribution! :smile:
But I can't release.

**Comment by boennemann** [comment]
Thanks for this PR! Is there any plan to release this to npm soon? It's a pitty this is sitting around on the main branch and it can't be used 😬

**Comment by voxpelli** [comment]
@boennemann My impression is that this module is deprecated 🤔 The `standard` module instead uses the `eslint-config-standard-jsx` one, hence why I didn’t roll a release of this one.

I’m tracking some of the remaining releases here: https://github.com/standard/eslint-config-standard/issues/229

**Comment by pjg** [comment]
@voxpelli I don't think `eslint-config-standard-jsx` fully replaces `eslint-config-standard-react`. From `eslint-config-standard-jsx` [README](https://github.com/standard/eslint-config-standard-jsx#usage):

> Even though this config is JSX only (no React), it makes use of [eslint-plugin-react](https://npmjs.com/package/eslint-plugin-react) for its generic JSX rules.
>
> (If you want React-specific rules too, consider using [eslint-config-standard-react](https://www.npmjs.com/package/eslint-config-standard-react) instead.)

EDIT: I compared the rules in both packages and they are completely different, so I don’t think `eslint-config-standard-react` is deprecated in any way. It complements `eslint-config-standard-jsx`. As such, any chance for an official npm release?

**Comment by mirismaili** [comment]
The current version on NPM ([v11.0.1](https://www.npmjs.com/package/eslint-config-standard-react/v/11.0.1) that is published a year ago) doesn't support ESLint 8 yet! Even there is no beta version.

**Comment by voxpelli** [comment]
I created an issue for it: https://github.com/standard/eslint-config-standard-react/issues/73

**Review by msedo8g8 — COMMENTED** [review]
Fucc

**Comment by derekhubbard** [comment]
Hey folks, just checking in. Any idea what the hold-up is in getting the released? Thanks in advance!

**Pull request merged**
