### PR TITLE
make install-peerdepsable

### PR DESCRIPTION
**Pull request by corysimmons**

### CODE REVIEW

**Comment by corysimmons** [comment]
https://github.com/standard/eslint-config-standard-react/issues/55

Pretty sure this PR will work but `npm link` and confirm on your end before merge.

Alternatively feel free to close. It's just a small QOL thing.

**Comment by feross** [comment]
Can you link to an example of other eslint shareable configs using this? Does the eslint project itself recommend this approach?

**Comment by corysimmons** [comment]
- https://www.npmjs.com/package/eslint-config-airbnb#eslint-config-airbnb-1
- https://github.com/wesbos/eslint-config-wesbos#local--per-project-install
- https://www.google.com/search?q="npx+install-peerdeps"+eslint

Interestingly, the official ESLint stance is to put all the configs you're relying on into deps and put all the plugins you're relying on into peerDeps... https://eslint.org/docs/developer-guide/shareable-configs#publishing-a-shareable-config

tbh this peerdeps stuff doesn't even fix my main gripe with eslint configs (bloating my package.json with 50 configs), but it at least makes the `npm i 50 different space separated packages with huge names` go away.. I wish there was a cleaner way to just include/use/extend all the libs.

**Comment by corysimmons** [comment]
Actually according to the rules for all this stuff it seems:

```
npm install --save-dev babel-eslint eslint-config-standard eslint-config-standard-react eslint-plugin-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node eslint-plugin-react
```

should be

## peerDeps because they're ["plugins"](https://nodejs.org/es/blog/npm/peer-dependencies/) (?):

> A plugin package is meant to be used with another "host" package, even though it does not always directly use the host package.

- eslint-plugin-standard
- eslint-plugin-promise
- eslint-plugin-import
- eslint-plugin-node
- eslint-plugin-react

## deps

> However, if your shareable config depends on a third-party parser or another shareable config, you can specify these packages as dependencies.

- babel-eslint
- eslint-config-standard
- eslint-config-standard-react

Dunno.. It's confusing and I'm sure people are doing it wrong all over the place, so it's impossible to depend on (most maintainers can't semver).

I think the correct solution is:

1. ES everything.
2. Include whatever you (the maintainer) want as a direct dep.
3. Leave it up other maintainers to ES their projects, and leave it up to the end-user to tree-shake their stuff.

Then everyone can just `yarn add -D eslint-config-standard-react`, `"eslintConfig": { "extends": ["eslint-config-standard-react"] }` without bloat in any bundle or taking up 30 lines of misc pkgs in every project's package.json.

**Comment by feross** [comment]
I opened an issue to track this here: https://github.com/standard/standard/issues/1345 since you closed this PR.

**Comment by corysimmons** [comment]
Thanks bro. 👍

**Pull request closed without merging**
