### PR TITLE
Disable react-specific linting rules (pure JSX)

### PR DESCRIPTION
**Pull request by 84564221**
Since JSX is intended to be used by various preprocessors (transpilers) to transform DOM tokens into standard ECMAScript and it's not a proposal to incorporate with the ECMAScript spec itself, the usage should not be restricted to only one library ([react](https://github.com/facebook/react)).

See feross/standard#367.

### CODE REVIEW

**Comment by dcousens** [comment]
NACK,  though maybe @feross we should move to create `eslint-config-standard-jsx` for the next standard version?
I'd be happy with these changes there.

**Comment by 84564221** [comment]
Would it not be better simply to rename this repository into `eslint-config-standard-jsx`?

**Comment by dcousens** [comment]
@askmatey and completely break repositories that are using this `eslint` config independently?

**Comment by 84564221** [comment]
The original idea of standard was to define a common, simplified coding standard. Standards are paper. I use paper to wipe my butt every day. That's how much that paper is worth. But I do not see any reason to include restrictions to a single library. React specific linting rules are bloat here.

**Comment by dcousens** [comment]
@feross seems to be re-occurring issue.
Did we want to relax the rules here and just make explicit React support a user-specified eslint extension in 6?

Alternatively, we leave this as is (so existing users don't start making mistakes),  and just make a new repository `eslint-config-standard-jsx` for 6.

**Comment by feross** [comment]
Thanks – this is done, though not via this PR.

standard v6 will remove all opinionated react rules, opting for just some simple JSX rules. https://github.com/feross/eslint-config-standard-jsx

**Comment by dcousens** [comment]
:+1:

**Comment by 84564221** [comment]
I told you

**Pull request closed without merging**
