### PR TITLE
Update eslintrc.json

### PR DESCRIPTION
**Pull request by dcousens**
IMHO, more of a patch than a breaking change.
This almost certainly erroneous behaviour otherwise.

### CODE REVIEW

**Comment by feross** [comment]
Released as 1.2.0.

**Comment by feross** [comment]
Dang, this had a typo. It's `jsx-no-duplicate-props` (plural). Fixed and published as 1.2.1.

**Comment by dcousens** [comment]
My bad @feross

Thanks :+1:

**Comment by dcousens** [comment]
Thanks :+1:

**Pull request merged**
